name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  schedule:
    # Every Saturday at 01:30 UTC
    - cron: "30 01 * * 6"
  workflow_dispatch:

env:
  GITHUB_ORG: beakthoven
  IMAGE_NAME: docker-images

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
          - name: arch
            target: arch
          - name: arch-devel
            target: arch-devel

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push ${{ matrix.variant.name }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          target: ${{ matrix.variant.target }}
          tags: ghcr.io/${{ env.GITHUB_ORG }}/${{ env.IMAGE_NAME }}:${{ matrix.variant.name }}
